"""Initial schema with users, swings, and analysis_results

Revision ID: 81bc5a82cc5b
Revises: 
Create Date: 2026-01-05 12:06:31.796766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '81bc5a82cc5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swing_id', sa.Integer(), nullable=False),
    sa.Column('skeletal_data', sa.JSON(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('frames_with_person', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('bat_trail', sa.JSON(), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('drill', sa.String(length=255), nullable=True),
    sa.Column('drill_explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['swing_id'], ['swings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_results_swing_id'), 'analysis_results', ['swing_id'], unique=True)
    op.add_column('swings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('swings', sa.Column('video_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_swings_user_id'), 'swings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'swings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('swings', 'drill_explanation')
    op.drop_column('swings', 'phase')
    op.drop_column('swings', 'drill')
    op.drop_column('swings', 'score')
    op.drop_column('swings', 'feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swings', sa.Column('feedback', sqlite.JSON(), nullable=True))
    op.add_column('swings', sa.Column('score', sa.INTEGER(), nullable=True))
    op.add_column('swings', sa.Column('drill', sa.VARCHAR(), nullable=True))
    op.add_column('swings', sa.Column('phase', sa.VARCHAR(), nullable=True))
    op.add_column('swings', sa.Column('drill_explanation', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'swings', type_='foreignkey')
    op.drop_index(op.f('ix_swings_user_id'), table_name='swings')
    op.drop_column('swings', 'video_url')
    op.drop_column('swings', 'user_id')
    op.drop_index(op.f('ix_analysis_results_swing_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
